import "./globals.css";
import type { Metadata } from "next";
import StoreProvider from "@/bootstrap/store-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className="grid justify-items-center">
          {children}
        </body>
      </StoreProvider>
    </html>
  );
}